name: Recurring Task Cron Job

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    env:
      TZ: "UTC" 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Cron Job Script
        run: node lib/jobs/cronForRecurrence.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
